### Практическое задание к уроку 6

In [22]:
import numpy as np

1. __Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):  
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],  
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].  
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy.
Полученные значения должны быть равны.  
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.__

In [ ]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [ ]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

Нахожу ковариацию:  
### $cov_{xy} = \mu_{xy}-\mu_x \mu_y$

In [ ]:
cov_xy = (zp * ks).mean() - (zp.mean() * ks.mean())
round(cov_xy, 2)

9157.84

In [ ]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Нахожу смещенные стандартные отклонения:  
### $\sigma = \sqrt{\frac{\sum_{i=1}^n (x-\overline x)^2}{n}}$

In [ ]:
std_x = np.sqrt(np.power(zp - zp.mean(), 2).sum() / len(zp))
round(std_x, 2)

59.12

In [ ]:
std_y = np.sqrt(np.power(ks - ks.mean(), 2).sum() / len(ks))
round(std_y, 2)

174.55

In [ ]:
round(np.std(zp), 2)

59.12

In [ ]:
round(np.std(ks), 2)

174.55

Нахожу коэффициент корреляции Пирсона: 
### $r_{xy} = \frac{cov_{xy}}{\sigma_x \sigma_y}$

In [ ]:
r_xy = cov_xy / (std_x * std_y)
round(r_xy, 2)

0.89

In [ ]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

2. __Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:  
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.  
Известно, что в генеральной совокупности IQ распределен нормально.  
Найдите доверительный интервал для математического ожидания с надежностью 0.95.__

Дано: $n=10,\,\,\, \alpha=0.05$  
Использую t-критерий для построения доверительного интервала.  
Нахожу среднее значение, стандартное отклонение и значение $t_{\alpha/2}$:  
$$\overline X = 118.1,\,\,\, \sigma=10.55,\,\,\, t_{\alpha/2}=2.262$$
### $$\overline X \pm t_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}=118.1 \pm 2.262 \cdot \frac{10.55}{\sqrt{10}}=118.1 \pm 7.54=\bigl[110.56, 125.64\bigr]$$

In [ ]:
s = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
s

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [ ]:
s.mean()

118.1

In [ ]:
round(np.std(s, ddof=1), 2)

10.55

In [ ]:
x_1 = s.mean() - 2.262 * (np.std(s, ddof=1) / np.sqrt(len(s)))
x_2 = s.mean() + 2.262 * (np.std(s, ddof=1) / np.sqrt(len(s)))
print(f'Доверительный интервал: [{round(x_1, 2)}, {round(x_2, 2)}]')

Доверительный интервал: [110.56, 125.64]


3. __Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.__

Дано: $n=27,\,\,\, \overline X=174.2,\,\,\, \sigma^2=25 \Rightarrow \sigma=5$  
Использую z-критерий для построения доверительного интервала. $Z_{\alpha/2}=1.96$  
$$\overline X \pm z_{\alpha/2} \cdot \frac{\sigma}{\sqrt{n}}=174.2 \pm 1.96 \cdot \frac{5}{\sqrt{27}}=174.2\pm 1.886=\bigl[172.31,176.09\bigr]$$

In [ ]:
y_1 = 174.2 - 1.96 * (np.sqrt(25) / np.sqrt(27))
y_2 = 174.2 + 1.96 * (np.sqrt(25) / np.sqrt(27))
print(f'Доверительный интервал: [{round(y_1, 2)}, {round(y_2, 2)}]')

Доверительный интервал: [172.31, 176.09]
