### Практическое задание к уроку 8

__Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.  
Даны значения роста в трех группах случайно выбранных спортсменов:  
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.  
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.  
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.__

In [7]:
import numpy as np
from scipy import stats

In [2]:
f = np.array([173, 175, 180, 178, 177, 185, 183, 182])
f

array([173, 175, 180, 178, 177, 185, 183, 182])

In [3]:
h = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
h

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [4]:
sh = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
sh

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

Нулевая гипотеза: $\mu_f = \mu_h = \mu_{sh}$  
Альтернативная гипотеза: $\mu_f \neq \mu_h \neq \mu_{sh}$  
Уровень значимости: $\alpha=0.05$

In [9]:
stats.f_oneway(f, h, sh)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

__Вывод:__ Получившееся значение pvalue меньше установленного уровня значимости $\alpha=0.05$. Исходя из этого можно утверждать, что найдены статестически значимые различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.